Traceback (most recent call last):
  File "/Users/kvarada/miniconda3/envs/jbook/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/kvarada/miniconda3/envs/jbook/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/kvarada/miniconda3/envs/jbook/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/kvarada/miniconda3/envs/jbook/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/kvarada/miniconda3/envs/jbook/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/kvarada/miniconda3/envs/jbook/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/kvarada/miniconda3/envs/jbook/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
dc.score(X_train, y_train)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[120], line 1[0m
[0;32m----> 1[0m [43mdc[49m[38;5;241;43m.[39;49m[43mscore[49m[43m([49m[43mX_train[49m[43m,[49m[43m [49m[43my_train[49m[43m)[49m

File [0;32m~/miniconda3/envs/cpsc330/lib/python3.10/site-packages/sklearn/dummy.py:451[0m, in [0;36mDummyClassifier.score[0;34m(self, X, y, sample_weight)[0m
[1;32m    449[0m [38;5;28;01mif[39;00m X [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[1;32m    450[0m     X [38;5;241m=[39m np[38;5;241m.[39mzeros(shape[38;5;241m=[39m([38;5;28mlen[39m(y), [38;5;241m1[39m))
[0;32m--> 451[0m [38;5;28;01mreturn[39;00m [38;5;28;43msuper[39;49m[43m([49m[43m)[49m[38;5;241;43m.[39;49m[43mscore[49m[43m([49m[43mX[49m[43m,[49m[43m [49m[43my[49m[43m,[49m[43m [49m[43msample_weight[49m[43m)[49m

File [0;32m~/miniconda3/envs/cpsc330/lib/python3.10/site-packages/sklearn/base.py:705[0m, in [0;36mClassifierMixin.score[0;34m(self, X, y, sample_weight)[0m
[1;32m    680[0m [38;5;250m[39m[38;5;124;03m"""[39;00m
[1;32m    681[0m [38;5;124;03mReturn the mean accuracy on the given test data and labels.[39;00m
[1;32m    682[0m 
[0;32m   (...)[0m
[1;32m    701[0m [38;5;124;03m    Mean accuracy of ``self.predict(X)`` w.r.t. `y`.[39;00m
[1;32m    702[0m [38;5;124;03m"""[39;00m
[1;32m    703[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mmetrics[39;00m [38;5;28;01mimport[39;00m accuracy_score
[0;32m--> 705[0m [38;5;28;01mreturn[39;00m [43maccuracy_score[49m[43m([49m[43my[49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mpredict[49m[43m([49m[43mX[49m[43m)[49m[43m,[49m[43m [49m[43msample_weight[49m[38;5;241;43m=[39;49m[43msample_weight[49m[43m)[49m

File [0;32m~/miniconda3/envs/cpsc330/lib/python3.10/site-packages/sklearn/utils/_param_validation.py:211[0m, in [0;36mvalidate_params.<locals>.decorator.<locals>.wrapper[0;34m(*args, **kwargs)[0m
[1;32m    205[0m [38;5;28;01mtry[39;00m:
[1;32m    206[0m     [38;5;28;01mwith[39;00m config_context(
[1;32m    207[0m         skip_parameter_validation[38;5;241m=[39m(
[1;32m    208[0m             prefer_skip_nested_validation [38;5;129;01mor[39;00m global_skip_validation
[1;32m    209[0m         )
[1;32m    210[0m     ):
[0;32m--> 211[0m         [38;5;28;01mreturn[39;00m [43mfunc[49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m    212[0m [38;5;28;01mexcept[39;00m InvalidParameterError [38;5;28;01mas[39;00m e:
[1;32m    213[0m     [38;5;66;03m# When the function is just a wrapper around an estimator, we allow[39;00m
[1;32m    214[0m     [38;5;66;03m# the function to delegate validation to the estimator, but we replace[39;00m
[1;32m    215[0m     [38;5;66;03m# the name of the estimator by the name of the function in the error[39;00m
[1;32m    216[0m     [38;5;66;03m# message to avoid confusion.[39;00m
[1;32m    217[0m     msg [38;5;241m=[39m re[38;5;241m.[39msub(
[1;32m    218[0m         [38;5;124mr[39m[38;5;124m"[39m[38;5;124mparameter of [39m[38;5;124m\[39m[38;5;124mw+ must be[39m[38;5;124m"[39m,
[1;32m    219[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;124mparameter of [39m[38;5;132;01m{[39;00mfunc[38;5;241m.[39m[38;5;18m__qualname__[39m[38;5;132;01m}[39;00m[38;5;124m must be[39m[38;5;124m"[39m,
[1;32m    220[0m         [38;5;28mstr[39m(e),
[1;32m    221[0m     )

File [0;32m~/miniconda3/envs/cpsc330/lib/python3.10/site-packages/sklearn/metrics/_classification.py:220[0m, in [0;36maccuracy_score[0;34m(y_true, y_pred, normalize, sample_weight)[0m
[1;32m    154[0m [38;5;250m[39m[38;5;124;03m"""Accuracy classification score.[39;00m
[1;32m    155[0m 
[1;32m    156[0m [38;5;124;03mIn multilabel classification, this function computes subset accuracy:[39;00m
[0;32m   (...)[0m
[1;32m    216[0m [38;5;124;03m0.5[39;00m
[1;32m    217[0m [38;5;124;03m"""[39;00m
[1;32m    219[0m [38;5;66;03m# Compute accuracy for each possible representation[39;00m
[0;32m--> 220[0m y_type, y_true, y_pred [38;5;241m=[39m [43m_check_targets[49m[43m([49m[43my_true[49m[43m,[49m[43m [49m[43my_pred[49m[43m)[49m
[1;32m    221[0m check_consistent_length(y_true, y_pred, sample_weight)
[1;32m    222[0m [38;5;28;01mif[39;00m y_type[38;5;241m.[39mstartswith([38;5;124m"[39m[38;5;124mmultilabel[39m[38;5;124m"[39m):

File [0;32m~/miniconda3/envs/cpsc330/lib/python3.10/site-packages/sklearn/metrics/_classification.py:84[0m, in [0;36m_check_targets[0;34m(y_true, y_pred)[0m
[1;32m     57[0m [38;5;28;01mdef[39;00m [38;5;21m_check_targets[39m(y_true, y_pred):
[1;32m     58[0m [38;5;250m    [39m[38;5;124;03m"""Check that y_true and y_pred belong to the same classification task.[39;00m
[1;32m     59[0m 
[1;32m     60[0m [38;5;124;03m    This converts multiclass or binary types to a common shape, and raises a[39;00m
[0;32m   (...)[0m
[1;32m     82[0m [38;5;124;03m    y_pred : array or indicator matrix[39;00m
[1;32m     83[0m [38;5;124;03m    """[39;00m
[0;32m---> 84[0m     [43mcheck_consistent_length[49m[43m([49m[43my_true[49m[43m,[49m[43m [49m[43my_pred[49m[43m)[49m
[1;32m     85[0m     type_true [38;5;241m=[39m type_of_target(y_true, input_name[38;5;241m=[39m[38;5;124m"[39m[38;5;124my_true[39m[38;5;124m"[39m)
[1;32m     86[0m     type_pred [38;5;241m=[39m type_of_target(y_pred, input_name[38;5;241m=[39m[38;5;124m"[39m[38;5;124my_pred[39m[38;5;124m"[39m)

File [0;32m~/miniconda3/envs/cpsc330/lib/python3.10/site-packages/sklearn/utils/validation.py:409[0m, in [0;36mcheck_consistent_length[0;34m(*arrays)[0m
[1;32m    407[0m uniques [38;5;241m=[39m np[38;5;241m.[39munique(lengths)
[1;32m    408[0m [38;5;28;01mif[39;00m [38;5;28mlen[39m(uniques) [38;5;241m>[39m [38;5;241m1[39m:
[0;32m--> 409[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[1;32m    410[0m         [38;5;124m"[39m[38;5;124mFound input variables with inconsistent numbers of samples: [39m[38;5;132;01m%r[39;00m[38;5;124m"[39m
[1;32m    411[0m         [38;5;241m%[39m [[38;5;28mint[39m(l) [38;5;28;01mfor[39;00m l [38;5;129;01min[39;00m lengths]
[1;32m    412[0m     )

[0;31mValueError[0m: Found input variables with inconsistent numbers of samples: [107502, 184]

